### PR TITLE
Set an empty subtrace on absent fold lore

### LINKED ISSUE #222: Bug: fold FSM handles empty states in incorrect way
Trace handler has sliders that is used to point on appropriate states in current and previous datas. These sliders are adjusted correspondingly to the fold lores (it's internal name of data states descriptors), and in its turn lores are chosen by value id that `fold` currently iterates on. 

The problem is `fold` handler doesn't do anything in case of absence of value in lores. This could cause undeterministic execution and errors in state merging process.

This issue is close to #221, they were split in order to better fixing.

### PR DESCRIPTION
**Pull request by monoid**
Closes #222

### CODE REVIEW

File: air/tests/test_module/issues/issue_222.rs [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+  (par
+   (par
+      (call "other_1" ("" "") [] $stream)
+      (call "other_2" ("" "") [] $stream))
+   (fold $stream j
+       (seq (call "other_id" ("" "") [j])
+            (next j)))))
+"#;
+
+    let mut other_id = create_avm(echo_call_service(), "other_id");
```
Comment (mikevoronov) [inline air/tests/test_module/issues/issue_222.rs:35]: I usually add a suffix `vm` to all such variables.

File: crates/air-lib/trace-handler/src/state_automata/fold_fsm/lore_applier.rs [hunk 2]
```diff
@@ -44,16 +44,20 @@ fn apply_fold_lore(
...
     let slider = match ctx_type {
         Previous => data_keeper.prev_slider_mut(),
         Current => data_keeper.current_slider_mut(),
     };
 
+    let fold_lore = match fold_lore {
+        Some(fold_lore) => fold_lore,
+        None => {
+            // create an empty subtrace
+            slider.set_position_and_len(slider.subtrace_len(), 0)?;
```
Comment (mikevoronov) [inline crates/air-lib/trace-handler/src/state_automata/fold_fsm/lore_applier.rs:56]: Using `slider.subtrace_len()` for a position is kinda confusing. From the other hand `slider` has a method `set_subtrace_len`, I suggest to use it instead.

File: crates/air-lib/trace-handler/src/state_automata/fold_fsm/lore_applier.rs [hunk 3]
```diff
@@ -44,16 +44,20 @@ fn apply_fold_lore(
...
-        Some(fold_lore) => fold_lore,
-        None => return Ok(()),
-    };
-
     let slider = match ctx_type {
         Previous => data_keeper.prev_slider_mut(),
         Current => data_keeper.current_slider_mut(),
     };
 
+    let fold_lore = match fold_lore {
```
Comment (mikevoronov) [inline crates/air-lib/trace-handler/src/state_automata/fold_fsm/lore_applier.rs:52]: I think that `if ...is_none()` would look better.

Comment (monoid) [reply crates/air-lib/trace-handler/src/state_automata/fold_fsm/lore_applier.rs]: We need value in the `Some` anyway.  I've refactored into a `match` statement instead of an expression.

File: air/tests/test_module/issues/issue_222.rs [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+
+    // The bug is triggered when (call "other_2" ...) result arrives to "other_id"
```
[the remark this answers is not in the document]
Comment (monoid) [reply air/tests/test_module/issues/issue_222.rs]: Yep, it was my idea too.

File: crates/air-lib/trace-handler/src/state_automata/fold_fsm/lore_applier.rs [hunk 5]
```diff
@@ -44,29 +44,31 @@ fn apply_fold_lore(
...
-                fold_lore.before_subtrace.begin_pos as _,
-                fold_lore.before_subtrace.subtrace_len as _,
-            )?;
-        }
-        After => {
-            slider.set_position_and_len(
-                fold_lore.after_subtrace.begin_pos as _,
-                fold_lore.after_subtrace.subtrace_len as _,
-            )?;
+    match fold_lore {
```
Comment (mikevoronov) [inline crates/air-lib/trace-handler/src/state_automata/fold_fsm/lore_applier.rs:52]: I'd say that `if` was better because it decouples one indentation level and the code becomes more understandable.

File: air/tests/test_module/issues/issue_222.rs [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+    let air_script = f!(r#"
+        (new $stream
+          (par
+           (par
+              (call "{other_1_id}" ("" "") [] $stream)
+              (call "{other_2_id}" ("" "") [] $stream))
+           (fold $stream j
+               (seq (call "{other_id}" ("" "") [j])
+                    (next j)))))
+"#);
```
Comment (mikevoronov) [inline air/tests/test_module/issues/issue_222.rs:37]: please indent it also

**Review by mikevoronov — COMMENTED** [review]
utACK

**Review by mikevoronov — APPROVED** [review]

**Comment by monoid** [comment]
I've concluded that the test in this PR is not weak, it perfectly demonstrates the problem.  I've renamed it.
