### PR TITLE
Fix Display of `Value::LastError` with a lambda

### LINKED ISSUE #263: `air_parser::ast::instruction_argument::Value` is incorrectly Display'ed in certain case
An argument of `%last_error%.$.message` is Display'ed as `%last_error%.$..message`.  It's a small typo in the `fn display_last_error`.

### PR DESCRIPTION
**Pull request by monoid**
There was a small typo in the `fn display_last_error`.

Closes #263

### CODE REVIEW

File: crates/air-lib/air-parser/src/ast/tests/instruction_arguments.rs [hunk 1]
```diff
@@ -0,0 +1,27 @@
+use crate::ast::Value;
+
+use air_lambda_ast::ValueAccessor;
+/*
```
Comment (mikevoronov) [inline crates/air-lib/air-parser/src/ast/tests/instruction_arguments.rs:4]: Place the copyright to the top

File: crates/air-lib/air-parser/src/ast/tests/instruction_arguments.rs [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+use non_empty_vec::NonEmpty;
+
+#[test]
+fn bug_263_last_error_lambda() {
```
Comment (mikevoronov) [inline crates/air-lib/air-parser/src/ast/tests/instruction_arguments.rs:22]: We use issue instead of bug for such names, and please add a link to the issue in github followign this example https://github.com/fluencelabs/aquavm/blob/master/air/tests/test_module/issues/issue_137.rs#L20

**Review by mikevoronov — APPROVED** [review]
utACK
